### ISSUE TITLE
拖拽偏移

### ISSUE THREAD

**Issue by shuiliang** [873391579/QQRed#2]
作者您好，控件我用的是 UIButton , 一按下拖拽，红点立即偏移到屏幕左上角了，而我的鼠标还在原来红点的位置（屏幕中心）

**Comment by zhuzhuxingtianxia** [comment]
是否使用了第三方布局，例如Masonry是不支持的！

**Comment by zhuzhuxingtianxia** [comment]
是否使用了第三方布局，例如Masonry是不支持的！

**Comment by shuiliang** [comment]
我用的是xib布局，写在UIStackview 里
